name: Release
on:
  push:
    tags: ['v*']

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            name: ibtop-linux-amd64
          - target: aarch64-unknown-linux-gnu  
            os: ubuntu-latest
            name: ibtop-linux-arm64
    
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      
      - uses: Swatinem/rust-cache@v2
      
      - name: Install cross
        uses: taiki-e/install-action@cross
        
      - name: Build
        run: cross build --release --target ${{ matrix.target }}
      
      - name: Strip binary  
        run: |
          if [[ "${{ matrix.target }}" == *"windows"* ]]; then
            cp target/${{ matrix.target }}/release/ibtop.exe ${{ matrix.name }}.exe
          else
            strip target/${{ matrix.target }}/release/ibtop
            cp target/${{ matrix.target }}/release/ibtop ${{ matrix.name }}
          fi
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}
          path: ${{ matrix.name }}*

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
      
      - name: Create release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create ${{ github.ref_name }} \
            --title "Release ${{ github.ref_name }}" \
            --generate-notes \
            **/ibtop-*